# Generated by Django 4.2.7 on 2023-11-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
                ('phone', models.IntegerField(null=True)),
                ('joined_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fotoproduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
    ]
