# Generated by Django 4.2.6 on 2023-11-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_foto_fotoproduk_delete_kategori_delete_produk'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='foto',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
